package DAL;
// Generated Jan 13, 2015 5:22:16 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Comment generated by hbm2java
 */
public class Comment  implements java.io.Serializable {


     private Integer id;
     private String comment;
     private String username;
     private Date datum;
     private Set spels = new HashSet(0);

    public Comment() {
    }

	
    public Comment(String comment, String username, Date datum) {
        this.comment = comment;
        this.username = username;
        this.datum = datum;
    }
    public Comment(String comment, String username, Date datum, Set spels) {
       this.comment = comment;
       this.username = username;
       this.datum = datum;
       this.spels = spels;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public Date getDatum() {
        return this.datum;
    }
    
    public void setDatum(Date datum) {
        this.datum = datum;
    }
    public Set getSpels() {
        return this.spels;
    }
    
    public void setSpels(Set spels) {
        this.spels = spels;
    }




}


