package DAL;
// Generated Jan 13, 2015 5:22:16 PM by Hibernate Tools 4.3.1



/**
 * Spel generated by hbm2java
 */
public class Spel  implements java.io.Serializable {


     private Integer id;
     private Category category;
     private Comment comment;
     private String titel;
     private String omschrijvingSpel;
     private String benodigdheden;
     private int counter;
     private int aantalPersonenVanaf;
     private int aantalPersonenTot;

    public Spel() {
    }

	
    public Spel(Category category, String titel, String omschrijvingSpel, String benodigdheden, int counter, int aantalPersonenVanaf, int aantalPersonenTot) {
        this.category = category;
        this.titel = titel;
        this.omschrijvingSpel = omschrijvingSpel;
        this.benodigdheden = benodigdheden;
        this.counter = counter;
        this.aantalPersonenVanaf = aantalPersonenVanaf;
        this.aantalPersonenTot = aantalPersonenTot;
    }
    public Spel(Category category, Comment comment, String titel, String omschrijvingSpel, String benodigdheden, int counter, int aantalPersonenVanaf, int aantalPersonenTot) {
       this.category = category;
       this.comment = comment;
       this.titel = titel;
       this.omschrijvingSpel = omschrijvingSpel;
       this.benodigdheden = benodigdheden;
       this.counter = counter;
       this.aantalPersonenVanaf = aantalPersonenVanaf;
       this.aantalPersonenTot = aantalPersonenTot;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Category getCategory() {
        return this.category;
    }
    
    public void setCategory(Category category) {
        this.category = category;
    }
    public Comment getComment() {
        return this.comment;
    }
    
    public void setComment(Comment comment) {
        this.comment = comment;
    }
    public String getTitel() {
        return this.titel;
    }
    
    public void setTitel(String titel) {
        this.titel = titel;
    }
    public String getOmschrijvingSpel() {
        return this.omschrijvingSpel;
    }
    
    public void setOmschrijvingSpel(String omschrijvingSpel) {
        this.omschrijvingSpel = omschrijvingSpel;
    }
    public String getBenodigdheden() {
        return this.benodigdheden;
    }
    
    public void setBenodigdheden(String benodigdheden) {
        this.benodigdheden = benodigdheden;
    }
    public int getCounter() {
        return this.counter;
    }
    
    public void setCounter(int counter) {
        this.counter = counter;
    }
    public int getAantalPersonenVanaf() {
        return this.aantalPersonenVanaf;
    }
    
    public void setAantalPersonenVanaf(int aantalPersonenVanaf) {
        this.aantalPersonenVanaf = aantalPersonenVanaf;
    }
    public int getAantalPersonenTot() {
        return this.aantalPersonenTot;
    }
    
    public void setAantalPersonenTot(int aantalPersonenTot) {
        this.aantalPersonenTot = aantalPersonenTot;
    }




}


